export const actionsTypes = {
  FILTER_OFFERS_BY_TECH: 'FILTER_OFFERS_BY_TECH',
  SEARCH_OFFER_BY_NAME: 'SEARCH_OFFER_BY_NAME',
  FILTER_OFFERS_BY_LOCATION: 'FILTER_OFFERS_BY_LOCATION',
  RESET_FILTERS: 'RESET_FILTERS',
  CHANGE_LOCATION: 'CHANGE_LOCATION',
  FETCH_OFFERS: 'FETCH_OFFERS',
  FETCH_OFFERS_ERROR: 'FETCH_OFFERS_ERROR',
  SET_OFFERS: 'SET_OFFERS',
  SET_OFFERS_ERROR: 'SET_OFFERS_ERROR',
  //MODAL
  FILTER_OFFERS_BY_EXPERIENCE: 'FILTER_OFFERS_BY_EXPERIENCE',
  FILTER_OFFERS_BY_EMPLOYMENTTYPE:'FILTER_OFFERS_BY_EMPLOYMENTTYPE',
  FILTER_OFFERS_BY_SALARY: 'FILTER_OFFERS_BY_SALARY',
  //AUTH
  SIGNUP_USER:'SIGNUP_USER',
  SIGNUP_USER_ERROR:'SIGNUP_USER_ERROR',
  LOGIN_USER:'LOGIN_USER',
  LOGIN_USER_ERROR:'LOGIN_USER_ERROR',
  LOGOUT_USER: 'LOGOUT_USER',

};
