export const actionsTypes = {
  FILTER_OFFERS_BY_TECH: 'FILTER_OFFERS_BY_TECH',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SEARCH_OFFER_BY_NAME: 'SEARCH_OFFER_BY_NAME',
  FILTER_OFFERS_BY_LOCATION: 'FILTER_OFFERS_BY_LOCATION',
  RESET_FILTERS: 'RESET_FILTERS',
};
