




export const offers = [
  {
    id: 1,
    title: 'Junior Js Developer',
    // salary: '3000 - 3200 PLN',
    salaryFrom: 3000,
    salaryTo: 3200,
    location: 'Warsaw',
    tech: 'js',
    logo: 'Logo',
    experience: 'Junior',
    companySize: 30,
    companyName: 'Netguru',
    employmentType: 'B2B',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },

  {
    id: 2,
    title: 'Mid Java Developer Lvl Ex 3 years',
    // salary: '6000 - 7500 PLN',
    salaryFrom: 6000,
    salaryTo: 7500,
    location: 'Krakow',
    tech: 'java',
    logo: 'Logo',
    experience: 'Mid',
    companySize: 50,
    companyName: 'ABB',
    employmentType: 'Permanent',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 3,
    title: 'Web Developer with HTML',
    // salary: '5000 - 6500 PLN',
    salaryFrom: 5000,
    salaryTo: 6500,
    location: 'Remote',
    tech: 'html',
    logo: 'Logo',
    experience: 'Mid',
    companySize: 10,
    companyName: 'IBPM',
    employmentType: 'B2B',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 4,
    title: 'PHP Developer ',
    // salary: '6000 - 7500 PLN',
    salaryFrom: 6000,
    salaryTo: 7500,
    location: 'Wroclaw',
    tech: 'php',
    logo: 'Logo',
    experience: 'Mid',
    companySize: 70,
    companyName: 'ABB',
    employmentType: 'B2B',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 5,
    title: 'Python Developer ',
    // salary: '9000 - 10500 PLN',
    salaryFrom: 9000,
    salaryTo: 10500,
    location: 'Poznań',
    tech: 'python',
    logo: 'Logo',
    experience: 'Mid',
    companySize: 20,
    companyName: 'Code & Papper',
    employmentType: 'Permanent',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 6,
    title: 'IOS Developer ',
    // salary: '5000 - 8500 PLN',
    salaryFrom: 5000,
    salaryTo: 8500,
    location: 'Trójmiasto',
    tech: 'mobile',
    logo: 'Logo',
    experience: 'Mid',
    companySize: 20,
    companyName: 'Polcode',
    employmentType: 'Mandate contract',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 7,
    title: 'QA tester',
    // salary: '12300 - 14000 PLN',
    salaryFrom: 12300,
    salaryTo: 14000,
    location: 'Śląsk',
    tech: 'testing',
    logo: 'Logo',
    experience: 'Senior',
    companySize: 10,
    companyName: 'ABB',
    employmentType: 'B2B',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 8,
    title: 'System Administrator',
    // salary: '9000 - 10500 PLN',
    salaryFrom: 9000,
    salaryTo: 10500,
    location: 'New York',
    tech: 'admin',
    logo: 'Logo',
    experience: 'Mid',
    companySize: 40,
    companyName: 'PDA IT Solutions',
    employmentType: 'Mandate contract',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 9,
    title: 'Junior Project Manager',
    // salary: '3100 - 3500 PLN',
    salaryFrom: 3100,
    salaryTo: 3500,
    location: 'Berlin',
    tech: 'pm',
    logo: 'Logo',
    experience: 'Junior',
    companySize: 50,
    companyName: 'ENNOVA',
    employmentType: 'B2B',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 10,
    title: 'Senior Java Developer',
    // salary: '6000 - 7500 PLN',
    salaryFrom: 6000,
    salaryTo: 7500,
    location: 'London',
    tech: 'java',
    logo: 'Logo',
    experience: 'Senior',
    companySize: 220,
    companyName: 'Code Apps',
    employmentType: 'Permanent',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 11,
    title: 'Senior Java Developer',
    // salary: '6000 - 7500 PLN',
    salaryFrom: 6000,
    salaryTo: 7500,
    location: 'London',
    tech: 'java',
    logo: 'Logo',
    experience: 'Senior',
    companySize: 220,
    companyName: 'Code Apps',
    employmentType: 'Permanent',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 12,
    title: 'Senior Java Developer',
    // salary: '6000 - 7500 PLN',
    salaryFrom: 6000,
    salaryTo: 7500,
    location: 'London',
    tech: 'java',
    logo: 'Logo',
    experience: 'Senior',
    companySize: 220,
    companyName: 'Code Apps',
    employmentType: 'Permanent',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 13,
    title: 'Senior Java Developer',
    // salary: '6000 - 7500 PLN',
    salaryFrom: 6000,
    salaryTo: 7500,
    location: 'London',
    tech: 'java',
    logo: 'Logo',
    experience: 'Senior',
    companySize: 220,
    companyName: 'Code Apps',
    employmentType: 'Permanent',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 14,
    title: 'Senior Java Developer',
    // salary: '6000 - 7500 PLN',
    salaryFrom: 6000,
    salaryTo: 7500,
    location: 'London',
    tech: 'java',
    logo: 'Logo',
    experience: 'Senior',
    companySize: 220,
    companyName: 'Code Apps',
    employmentType: 'Permanent',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 15,
    title: 'Senior Java Developer',
    // salary: '6000 - 7500 PLN',
    salaryFrom: 6000,
    salaryTo: 7500,
    location: 'London',
    tech: 'java',
    logo: 'Logo',
    experience: 'Senior',
    companySize: 220,
    companyName: 'Code Apps',
    employmentType: 'Permanent',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 16,
    title: 'Senior Java Developer',
    // salary: '6000 - 7500 PLN',
    salaryFrom: 6000,
    salaryTo: 7500,
    location: 'London',
    tech: 'java',
    logo: 'Logo',
    experience: 'Senior',
    companySize: 220,
    companyName: 'Code Apps',
    employmentType: 'Permanent',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
  {
    id: 17,
    title: 'Senior Java Developer',
    // salary: '6000 - 7500 PLN',
    salaryFrom: 6000,
    salaryTo: 7500,
    location: 'London',
    tech: 'java',
    logo: 'Logo',
    experience: 'Senior',
    companySize: 220,
    companyName: 'Code Apps',
    employmentType: 'Permanent',
    jobDescription:
      'As a JavaScript/TypeScript Developer, you will be working on one of several projects which we develop for our core clients across the US and Europe. Our clients range from established US/EU start-ups with a solid customer base to bigger multinational organisations. All of them develop sophisticated products which heavily rely on Javascript and Typescript technologies for both frontend and backend services. In our projects you will have autonomy within the role as well as opportunity to contribute to the overall success of the project. Our projects allow for a direct interaction with clients and offer a very agile and low-overhead work environment',
    aboutCompany:
      'Netguru builds digital products that let people do things differently. Share your challenge with our team, and we’ll work with you to deliver a revolutionary digital product. Our clients have changed the way people do banking, listen to music, learn languages, and rent bikes. Their products have been featured in TechCrunch, Business Insider, and Product Hunt.',
  },
];
